<?xml version="1.0" encoding="utf-8"?>
<log>
<entry code="info" level="info">
 <message>[info] Activation of plug-in DQC Rules Validator successful, version Check version using Tools->DQC->Version on the GUI or --dqc-version on the command line. - validate/DQC </message>
 <ref href="validate/DQC"/></entry>
<entry code="info" level="info">
 <message>[info] Activation of plug-in SEC Inline Transforms successful, version 1.0.0.178. - transforms/SEC </message>
 <ref href="transforms/SEC"/></entry>
<entry code="info" level="info">
 <message>[info] Xule version: 3.0.22716 - </message>
 <ref href=""/></entry>
<entry code="info" level="info">
 <message>[info] loaded in 2.81 secs at 2019-02-07T18:28:12 - http://www.sec.gov/Archives/edgar/data/1527428/000158064217000024/ait-20161214.xml </message>
 <ref href="http://www.sec.gov/Archives/edgar/data/1527428/000158064217000024/ait-20161214.xml"/></entry>
<entry code="info" level="info">
 <message>[info] Using ruleset None - ait-20161214.xml </message>
 <ref href="ait-20161214.xml"/></entry>
<entry code="xule" level="error">
 <message>[xule] Cannot determine which rule set to use for the filing. Check the rule set map at '/Users/campbellpryde/Library/Application Support/Arelle/plugin/xule/rulesetMap.json'. - ait-20161214.xml </message>
 <ref href="ait-20161214.xml"/></entry>
<entry code="exception:XuleRuleSetError" level="error">
 <message instance="ait-20161214.xml" error="The rule set to used could not be determined. Check that there is a rule set map at /Users/campbellpryde/Library/Application Sup...">[exception:XuleRuleSetError] Instance validation exception: The rule set to used could not be determined. Check that there is a rule set map at /Users/campbellpryde/Library/Application Support/Arelle/plugin/xule/rulesetMap.json and verify that there is an appropiate mapping for the filing., instance: ait-20161214.xml - http://www.sec.gov/Archives/edgar/data/1527428/000158064217000024/ait-20161214.xml 
Traceback (most recent call last):
  File &quot;/Users/arelle/hfdev/arelle/Validate.py&quot;, line 112, in validate
  File &quot;/Users/arelle/hfdev/arelle/ValidateXbrl.py&quot;, line 520, in validate
  File &quot;/Applications/Arelle.app/Contents/MacOS/plugin/xule/__init__.py&quot;, line 861, in xuleValidate
    runXule(_cntlr, _options, val.modelXbrl, xule_validator['map_name'])
  File &quot;/Applications/Arelle.app/Contents/MacOS/plugin/xule/__init__.py&quot;, line 787, in runXule
    raise xr.XuleRuleSetError('The rule set to used could not be determined. Check that there is a rule set map at {} and verify that there is an appropiate mapping for the filing.'.format(xu.get_rule_set_map_file_name(cntlr, rule_set_map)))
xule.XuleRuleSet.XuleRuleSetError: The rule set to used could not be determined. Check that there is a rule set map at /Users/campbellpryde/Library/Application Support/Arelle/plugin/xule/rulesetMap.json and verify that there is an appropiate mapping for the filing.</message>
 <ref href="http://www.sec.gov/Archives/edgar/data/1527428/000158064217000024/ait-20161214.xml"/></entry>
<entry code="info" level="info">
 <message>[info] validated in 0.63 secs - http://www.sec.gov/Archives/edgar/data/1527428/000158064217000024/ait-20161214.xml </message>
 <ref href="http://www.sec.gov/Archives/edgar/data/1527428/000158064217000024/ait-20161214.xml"/></entry>
</log>
